#!/usr/bin/env python3
farms = [{"name": "NE Farm", "agriculture": ["sheep", "cows", "pigs", "chickens", "llamas", "cats"]},
         {"name": "W Farm", "agriculture": ["pigs", "chickens", "llamas"]},
         {"name": "SE Farm", "agriculture": ["chickens", "carrots", "celery"]}]


#Write a for loop that returns all the animals from the NE Farm!

i=0
for Ever_Item in farms:
    if farms[i]["name"] == "NE Farm":
        print (farms[i]["agriculture"])
    i=i+1
#Ask a user to choose a farm (NE Farm, W Farm, or SE Farm). Return the plants/animals that are raised on that farm.

e=0
print("Choose a farm (NE Farm, W Farm, or SE Farm) ")
FarmName = input("name>>>")


for Items in farms:
    if farms[e]["name"] == FarmName:
        print (farms[e]["agriculture"])
    e=e+1

    



    


   




